export const INIT_FILTER_RULE = 'INIT_FILTER_RULE';
export const ADD_FILTER_RULE = 'ADD_FILTER_RULE';
export const DEL_FILTER_RULE = 'DEL_FILTER_RULE';
export const UPDATE_FILTER_RULE = 'UPDATE_FILTER_RULE';
export const DELETE_FILTER_RULE = 'DELETE_FILTER_RULE';
